### ISSUE TITLE
Dependency not created

### ISSUE THREAD

**Issue by DrankRock** [jmarkowski/codeviz#6]
Hello !
I'm trying to use this tool, I've tried withn Python3.7 and 3.10, and the links between the file names are not created, so I have the nodes of the graphes but not the link. 

My result is as follow : 
![codeviz](https://user-images.githubusercontent.com/32172257/212874808-00af48a8-1771-4b14-8107-7508f42a2976.png)

Thank you !

**Comment by jmarkowski** [comment]
What's the directory structure look like?

**Comment by xiudeming** [comment]
@jmarkowski hi, I met the same issue, I guess it is probably due to get_edges in case of recursive directories

**Comment by jmarkowski** [comment]
Fixed now by PR #10
